# Generated by Django 5.1.1 on 2024-11-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('role', models.CharField(choices=[('User', 'User'), ('Worker', 'Worker')], max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('bank_name', models.CharField(blank=True, max_length=50)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('npwp', models.CharField(blank=True, max_length=20, unique=True)),
                ('mypay_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user_level', models.CharField(blank=True, max_length=10)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('completed_orders', models.IntegerField(blank=True, default=0)),
                ('job_category', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
